### ISSUE TITLE
How to set a custom value of the AceEditor Field?

### ISSUE THREAD

**Issue by touqeershafi** [riodwanto/filament-ace-editor#3]
I'm using the following code to make the AceEditor However its not rendering the value of the field.
```php
$form->schema([
            Tabs::make("container")->tabs([
                Tab::make("name")->schema([
                    AceEditor::make("name")->hiddenLabel()
         ]),
     ])
]);
```
Below is the screenshot.
![image](https://github.com/riodwanto/filament-ace-editor/assets/4585116/2e5f1a23-b7f9-4642-99ed-a1197afed8ec)

Laravel: 10x
riodwanto/filament-ace-editor: 1.0

**Comment by riodwanto** [comment]
Hi @touqeershafi 

Your code is fine. Just make sure the `name` u define has value. u can add this `formatStateUsing(fn ($state) => dd($state))` to dump value.
